"""Tests for the typed claims layer (plan 002a headline family + plan 007 framing family).

  (a) round-trip     — `ClaimSet.add()` returns each claim's `rendered`; `to_json()`
                       serializes both claims + the `families_migrated` key.
  (b) manifest-write — a real `blocking_path.main()` render writes `<report>.claims.json`
                       beside the report, carrying a `headline_slowest` claim (and, plan
                       007, the migrated `pole_role_line` / `pole_gate_prompt` framing
                       claims, plus the Tier-2 runner-minute family) whose `rendered`
                       sentence appears verbatim in the report.
  (c) comparator red/green — `verify_report.check_headline_slowest_matches_stamp` PASSES
                       on the good manifest and FAILS when the manifest's
                       `headline_slowest.subject` is corrupted off the stamped
                       `critical_path_check`. (The committed form of the manual
                       red/green proof from this plan.)
  (d) text floor (plan 007) — a crafted but internally-consistent manifest cannot launder
                       a prose headline that names a different check than the stamp.

The framing-vocabulary coverage check and the anti-unregistered-claim source lint (plan
007) live in `test_verify_report_self.py`.

(b)/(c) reuse the offline-e2e gh-replay fixture corpus (fixtures/gh_replay/): the
same synthetic repo + recorded gh responses `test_offline_pipeline_e2e.py` drives,
so the findings.json is generated by the REAL pipeline, offline and deterministic.

Run: pytest -v skills/ci-speedup/tests/test_claims_layer.py
"""
from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

_SKILL_DIR = Path(__file__).resolve().parents[1]
_SCRIPTS = _SKILL_DIR / "scripts"
_VERIFY = _SKILL_DIR / "tests" / "verify_report.py"
_FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures" / "gh_replay"

sys.path.insert(0, str(_SCRIPTS))
import claims  # noqa: E402  (uniquely-named same-skill module)

# The synthetic repo/workflow the committed gh-replay corpus was recorded against —
# kept in lockstep with `test_offline_pipeline_e2e.py` (`_REPO` must match the
# owner/name baked into every fixture filename; `_WF_YAML` must match the workflow
# behind the `contents/.github/workflows/ci.yml` fixture).
_REPO = "synthetic/repo"
_WF_YAML = """name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
"""


def _load_verify_report():
    # Load THIS skill's verify_report by path under a unique name (ci-secure ships one
    # too, so a plain `import verify_report` can bind the wrong module on the shared
    # pytest pythonpath). Mirrors test_verify_report_self.py's collision-proof loader.
    name = "ci_speedup_verify_report_claims"
    spec = importlib.util.spec_from_file_location(name, _VERIFY)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def _init_repo(root: Path) -> None:
    (root / ".github" / "workflows").mkdir(parents=True)
    (root / ".github" / "workflows" / "ci.yml").write_text(_WF_YAML, encoding="utf-8")
    env = {**os.environ,
           "GIT_AUTHOR_NAME": "ci-speedup-test", "GIT_AUTHOR_EMAIL": "test@example.com",
           "GIT_COMMITTER_NAME": "ci-speedup-test", "GIT_COMMITTER_EMAIL": "test@example.com"}
    subprocess.run(["git", "init", "-q"], cwd=root, check=True, env=env)
    subprocess.run(["git", "add", ".github"], cwd=root, check=True, env=env)
    subprocess.run(["git", "commit", "-q", "-m", "init"], cwd=root, check=True, env=env)


def _replay_env() -> dict:
    env = dict(os.environ)
    env["CI_SPEEDUP_GH_FIXTURES"] = str(_FIXTURES_DIR)
    env.pop("CI_SPEEDUP_GH_RECORD", None)  # never record over a committed corpus
    return env


@pytest.fixture(scope="module")
def rendered_offline(tmp_path_factory) -> dict:
    """Generate findings.json via the offline gh-replay pipeline, then render it
    through `blocking_path.main()` to a real report + `<report>.claims.json`.
    Module-scoped so (b) and (c) share one render. Returns paths + parsed manifest."""
    tmp = tmp_path_factory.mktemp("claims_offline")
    repo_root = tmp / "repo"
    findings_path = tmp / "findings.json"
    report_path = tmp / "report.md"
    _init_repo(repo_root)
    env = _replay_env()

    run = subprocess.run(
        [sys.executable, str(_SCRIPTS / "run.py"),
         "--root", str(repo_root), "--out", str(findings_path), "--repo", _REPO],
        capture_output=True, text=True, env=env, timeout=60,
    )
    assert run.returncode == 0, f"run.py failed:\n{run.stdout}\n{run.stderr}"

    render = subprocess.run(
        [sys.executable, str(_SCRIPTS / "blocking_path.py"),
         "--in", str(findings_path), "--out", str(report_path)],
        capture_output=True, text=True, env=env, timeout=60,
    )
    assert render.returncode == 0, f"blocking_path.py failed:\n{render.stderr}"

    manifest_path = report_path.parent / (report_path.name + ".claims.json")
    assert manifest_path.exists(), "render did not write <report>.claims.json"
    return {
        "findings_path": findings_path,
        "report_path": report_path,
        "manifest_path": manifest_path,
        "report_text": report_path.read_text(encoding="utf-8"),
        "manifest": json.loads(manifest_path.read_text(encoding="utf-8")),
    }


# --- (a) round-trip ----------------------------------------------------------
def test_claimset_round_trip_add_returns_rendered_and_to_json_serializes_both():
    cs = claims.ClaimSet()
    c1 = claims.Claim(kind="headline_slowest", subject="CI / test",
                      fields={"merge_dur": "3m 17s"},
                      rendered="**3m 17s until all checks finish** - `CI / test` is the "
                               "slowest check a typical PR waits on. ")
    c2 = claims.Claim(kind="pole_role_line", subject="Build",
                      fields={"lead_floor": "6m 58s"},
                      rendered="Runs concurrently behind `Build` (6m 58s); ...")
    # add() returns the exact rendered string (so a call site can inline it).
    assert cs.add(c1) == c1.rendered
    assert cs.add(c2) == c2.rendered

    out = cs.to_json()
    assert list(out.keys()) == ["claims", "families_migrated"]
    assert out["families_migrated"] == ["headline", "slowest_gate_framing", "runner_minutes"]
    assert len(out["claims"]) == 2
    assert out["claims"][0] == {"kind": "headline_slowest", "subject": "CI / test",
                                "fields": {"merge_dur": "3m 17s"}, "rendered": c1.rendered}
    assert out["claims"][1] == {"kind": "pole_role_line", "subject": "Build",
                                "fields": {"lead_floor": "6m 58s"}, "rendered": c2.rendered}
    # round-trips through JSON unchanged (it is what gets written to disk).
    assert json.loads(json.dumps(out)) == out


def test_claimset_add_rejects_an_unregistered_kind():
    """`KNOWN_KINDS` is a closed vocabulary; `add()` must raise on an unregistered
    kind (a renderer typo, or a new kind wired in but not registered) rather than
    silently emit a manifest with an unrecognized kind that nothing catches until
    plan 007's coverage lint. Guards against a future edit deleting the check."""
    cs = claims.ClaimSet()
    bogus = claims.Claim(kind="not_a_real_kind", subject="X",
                         fields={}, rendered="whatever")
    with pytest.raises(ValueError, match="unknown claim kind"):
        cs.add(bogus)
    # nothing was appended, and every declared KNOWN_KINDS value is accepted.
    assert cs.to_json()["claims"] == []
    for k in claims.KNOWN_KINDS:
        assert cs.add(claims.Claim(kind=k, subject="s", fields={}, rendered="r")) == "r"


# --- (b) manifest-write-on-render --------------------------------------------
def test_render_writes_claims_manifest_with_verbatim_headline_claim(rendered_offline):
    manifest = rendered_offline["manifest"]
    report = rendered_offline["report_text"]
    assert "headline" in manifest["families_migrated"]
    headline = [c for c in manifest["claims"] if c["kind"] == "headline_slowest"]
    assert headline, "no headline_slowest claim in the manifest"
    for c in headline:
        assert c["subject"], "headline claim carries an empty subject"
        assert c["rendered"] in report, (
            "headline claim's rendered sentence is not in the report verbatim: "
            f"{c['rendered']!r}")
        # exactly once — the manifest<->prose bind the comparator relies on.
        assert report.count(c["rendered"]) == 1


def test_render_writes_migrated_framing_family_claims(rendered_offline):
    # Plan 007: the offline single-pole corpus exercises the `gate_is_slowest` role label (5014 ->
    # pole_role_line) and the generic agent-prompt gate line (2151 -> pole_gate_prompt). Both must
    # land in the manifest with their rendered sentence verbatim in the report, and the manifest
    # must declare the slowest_gate_framing family.
    manifest = rendered_offline["manifest"]
    report = rendered_offline["report_text"]
    assert "slowest_gate_framing" in manifest["families_migrated"]
    by_kind = {}
    for c in manifest["claims"]:
        by_kind.setdefault(c["kind"], []).append(c)
    for kind in ("pole_role_line", "pole_gate_prompt"):
        claims_of_kind = by_kind.get(kind, [])
        assert claims_of_kind, f"no {kind} claim in the offline manifest"
        for c in claims_of_kind:
            assert c["subject"], f"{kind} claim carries an empty subject"
            assert c["rendered"] in report, (
                f"{kind} claim's rendered sentence is not in the report verbatim: {c['rendered']!r}")


# --- (c) comparator red/green ------------------------------------------------
def test_headline_comparator_passes_good_manifest_fails_corrupted_subject(rendered_offline):
    vr = _load_verify_report()
    report = rendered_offline["report_text"]
    findings_path = rendered_offline["findings_path"]
    report_path = rendered_offline["report_path"]
    manifest_path = rendered_offline["manifest_path"]
    good_manifest_json = manifest_path.read_text(encoding="utf-8")

    # GREEN: the untouched manifest agrees with the stamped critical_path_check.
    ok = vr.check_headline_slowest_matches_stamp(report, findings_path, report_path)
    assert ok.ok and not ok.skipped, f"good manifest should PASS, got: {ok.detail}"
    assert "manifest" in ok.detail, (
        "expected the manifest path (not the text-parsing fallback) to have run: "
        f"{ok.detail}")

    # RED: corrupt the headline claim's subject off the stamp -> the comparator FAILS.
    corrupt = json.loads(good_manifest_json)
    n_corrupted = 0
    for c in corrupt["claims"]:
        if c["kind"] == "headline_slowest":
            c["subject"] = "Totally Wrong Check That Is Not The Stamp"
            n_corrupted += 1
    assert n_corrupted >= 1, "fixture had no headline_slowest claim to corrupt"
    manifest_path.write_text(json.dumps(corrupt, indent=2), encoding="utf-8")
    try:
        bad = vr.check_headline_slowest_matches_stamp(report, findings_path, report_path)
        assert not bad.ok and not bad.skipped, (
            "a manifest whose subject != stamped critical_path_check must FAIL, "
            f"got ok={bad.ok} skipped={bad.skipped}: {bad.detail}")
        assert "Totally Wrong Check" in bad.detail
    finally:
        # restore the good manifest so nothing downstream sees the corruption.
        manifest_path.write_text(good_manifest_json, encoding="utf-8")

    # restored -> GREEN again (proves the corruption, not some cache, drove the RED).
    ok2 = vr.check_headline_slowest_matches_stamp(report, findings_path, report_path)
    assert ok2.ok and not ok2.skipped, f"restored manifest should PASS, got: {ok2.detail}"


# A minimal report + findings whose HEADLINE PROSE names a check that is NOT the stamped
# critical_path_check — so the text-parsing path FAILS. Used to prove a headline-less
# manifest is never WEAKER than no manifest (it must FAIL too, not SKIP).
_HEADLINE_LINE = ("**3m until all checks finish** - `RealCheck` is the slowest check a "
                  "typical PR waits on.")
_WRONG_STAMP_REPORT = f"""# demo - why is the merge slow?

## Long pole 1: `ci.yml` - RealCheck - 3m

{_HEADLINE_LINE}
"""
# stamp != the `RealCheck` the prose names -> a faithful gate must FAIL.
_WRONG_STAMP_FINDINGS = {"pr_critical_path": {"critical_path_check": "DifferentCheck"}}


def _write_case(tmp_path: Path, manifest_obj) -> tuple[str, Path, Path]:
    """Write the wrong-stamp report + findings, plus (optionally) a claims manifest.
    `manifest_obj is None` -> no manifest file. Returns (report_text, findings_path,
    report_path)."""
    tmp_path.mkdir(parents=True, exist_ok=True)
    report_path = tmp_path / "report.md"
    report_path.write_text(_WRONG_STAMP_REPORT, encoding="utf-8")
    findings_path = tmp_path / "findings.json"
    findings_path.write_text(json.dumps(_WRONG_STAMP_FINDINGS), encoding="utf-8")
    if manifest_obj is not None:
        (tmp_path / "report.md.claims.json").write_text(
            json.dumps(manifest_obj), encoding="utf-8")
    return report_path.read_text(encoding="utf-8"), findings_path, report_path


def test_headline_less_manifest_falls_back_to_text_never_weaker(tmp_path):
    # THE BUG THIS PINS: a manifest declaring "headline" migrated but carrying no usable
    # headline_slowest claim must NOT SKIP — that would be strictly weaker than no manifest
    # (the text path would FAIL a wrong headline). It must fall back to the text path and
    # FAIL, exactly like the no-manifest baseline.
    vr = _load_verify_report()

    # Baseline: NO manifest -> the text path FAILs (prose `RealCheck` != stamp `DifferentCheck`).
    report, fp, rp = _write_case(tmp_path / "none", None)
    base = vr.check_headline_slowest_matches_stamp(report, fp, rp)
    assert not base.ok and not base.skipped, (
        f"no-manifest baseline should FAIL a wrong headline, got "
        f"ok={base.ok} skipped={base.skipped}: {base.detail}")

    # Each of these manifests declares "headline" migrated but yields NO usable
    # headline_slowest claim; every one must behave IDENTICALLY to the no-manifest baseline
    # (FAIL via the text fallback), never SKIP.
    headline_less_manifests = [
        {"families_migrated": ["headline"], "claims": []},                       # empty claims
        {"families_migrated": ["headline"], "claims": "not a list"},             # wrong-type claims
        {"families_migrated": ["headline"],                                      # only other kinds
         "claims": [{"kind": "pole_role_line", "subject": "X", "fields": {},
                     "rendered": "Runs concurrently behind `X` (1m)."}]},
        {"families_migrated": ["headline"], "claims": [{"not": "a claim dict entry"}, 42]},
    ]
    for i, m in enumerate(headline_less_manifests):
        report, fp, rp = _write_case(tmp_path / f"headless{i}", m)
        got = vr.check_headline_slowest_matches_stamp(report, fp, rp)
        assert not got.ok and not got.skipped, (
            f"headline-less manifest #{i} must FAIL via the text fallback (never SKIP) — "
            f"same as no manifest; got ok={got.ok} skipped={got.skipped}: {got.detail}")
        # identical verdict AND identical detail to the no-manifest baseline: proves the
        # fallback is byte-for-byte "as if no manifest", not merely "also fails".
        assert got.detail == base.detail, (
            f"headline-less manifest #{i} should read EXACTLY like the no-manifest path:\n"
            f"{got.detail!r}\nvs\n{base.detail!r}")

    # And a WELL-FORMED manifest (subject == stamp, rendered present once) still PASSES via
    # the manifest path — the fix doesn't break the happy path.
    good_report_path = tmp_path / "good"
    good_report_path.mkdir()
    good_line = ("**3m until all checks finish** - `DifferentCheck` is the slowest check a "
                 "typical PR waits on.")
    (good_report_path / "report.md").write_text(
        f"# demo\n\n## Long pole 1: `ci.yml` - DifferentCheck - 3m\n\n{good_line}\n",
        encoding="utf-8")
    (good_report_path / "findings.json").write_text(
        json.dumps(_WRONG_STAMP_FINDINGS), encoding="utf-8")  # stamp == DifferentCheck
    (good_report_path / "report.md.claims.json").write_text(json.dumps(
        {"families_migrated": ["headline"],
         "claims": [{"kind": "headline_slowest", "subject": "DifferentCheck",
                     "fields": {}, "rendered": good_line}]}), encoding="utf-8")
    good = vr.check_headline_slowest_matches_stamp(
        (good_report_path / "report.md").read_text(encoding="utf-8"),
        good_report_path / "findings.json", good_report_path / "report.md")
    assert good.ok and not good.skipped, f"well-formed manifest should PASS, got: {good.detail}"
    assert "manifest" in good.detail


def test_lying_manifest_cannot_override_prose_floor(tmp_path):
    # Plan 007 text floor (folds the final review's open lying-manifest finding): a crafted manifest
    # that is INTERNALLY consistent — its headline_slowest.subject == the stamp, and its rendered
    # sentence appears exactly once — must STILL fail when the report's PROSE headline names a
    # different check than the stamp. The manifest can strengthen the text check, never replace it.
    vr = _load_verify_report()
    # Prose headline names `RealCheck`; the data layer stamped `DifferentCheck`. A benign backing
    # sentence gives the crafted headline_slowest claim something to bind to (present exactly once).
    report = _WRONG_STAMP_REPORT + "\nA benign backing sentence that appears once.\n"
    manifest = {"families_migrated": ["headline", "slowest_gate_framing"],
                "claims": [{"kind": "headline_slowest", "subject": "DifferentCheck", "fields": {},
                            "rendered": "A benign backing sentence that appears once."}]}
    rp = tmp_path / "report.md"
    rp.write_text(report, encoding="utf-8")
    fp = tmp_path / "findings.json"
    fp.write_text(json.dumps(_WRONG_STAMP_FINDINGS), encoding="utf-8")  # stamp == DifferentCheck
    (tmp_path / "report.md.claims.json").write_text(json.dumps(manifest), encoding="utf-8")
    got = vr.check_headline_slowest_matches_stamp(report, fp, rp)
    assert not got.ok and not got.skipped, (
        f"a lying manifest must FAIL via the text floor, got ok={got.ok} skipped={got.skipped}: "
        f"{got.detail}")
    assert "lying-manifest guard" in got.detail
    # Control: the SAME crafted manifest with a prose headline that AGREES with the stamp passes
    # (the floor only bites a CONTRADICTING prose headline, not the manifest happy path).
    agree = _WRONG_STAMP_REPORT.replace("RealCheck", "DifferentCheck") + \
        "\nA benign backing sentence that appears once.\n"
    rp2 = tmp_path / "agree.md"
    rp2.write_text(agree, encoding="utf-8")
    (tmp_path / "agree.md.claims.json").write_text(json.dumps(manifest), encoding="utf-8")
    ok = vr.check_headline_slowest_matches_stamp(agree, fp, rp2)
    assert ok.ok and not ok.skipped, f"agreeing prose+manifest should PASS, got: {ok.detail}"
